esphome:
  name: mclh-09-gateway
preferences:
  flash_write_interval: 20min # should be much bigger than ble_client update_interval

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
  reboot_timeout: 0s
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
ota:
  - platform: esphome
    password: !secret ota_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
myhomeiot_ble_host:

mclh_09_gateway:
  id: my_mclh_09
  interval: 15min
  error_counting: true
  raw_soil: false # set to 'true' for raw soil values (without interpolate)
  mac_address:
    - !secret mclh09_001_mac
    - !secret mclh09_002_mac
    - !secret mclh09_003_mac
    - !secret mclh09_004_mac

button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic
  - platform: template
    name: "Force update"
    entity_category: diagnostic
    on_press:
      - mclh_09_gateway.force_update:
          id: my_mclh_09

# Fake sensor to prevent error "has no member named 'register_sensor'"
sensor:
  - platform: template
    name: "Template Sensor"
    internal: true

# Fake select to prevent error "has no member named 'register_select'"
select:
  - platform: template
    name: "Template select"
    optimistic: true
    internal: true
    options:
      - one
      - two
    initial_option: two

external_components:
  - source: github://myhomeiot/esphome-components
  - source: github://dvb6666/esphome-components
