esphome:
  name: neptun-smart
  friendly_name: Neptun Smart
  # platformio_options:
  #   build_flags: -Wno-sequence-point # for eps8266 to disable compiler warnings

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
# api:
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

mdns:
  disabled: true
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_pass
  log_topic: null
  discover_ip: false
  # discovery: false
  homed_custom:
    # topic_prefix: homed319
    # discovery: true

modbus_tcp:
  # IP-address of ESP32 module (NOT Tuya Smart module!!!) into Neptun Smart
  ip_address: !secret neptun_ip
  # port for Neptun Smart modbus service
  port: 503
  # raw data dump for debug
  # raw_data: true

neptun_smart:
  # binary sensor to signal if TCP connection lost
  connection_status: Connection Status
  # dual zone mode control; after changing NEED REBOOT Esp to show/hide zone2 controls
  dual_zone_mode: Dual Zone
  # zone valves state control
  valve_zone_1: Zone 1
  # valve_zone_2: Zone 2
  # binary sensors to signal zone alerts
  alert_zone_1: Alert Zone 1
  # alert_zone_2: Alert Zone 2
  # switches to control: floor washing mode, adding wireless sessor mode, close on wireless sensor lost, child lock
  floor_washing_mode: Floor Washing
  add_wireless_mode: Add Wireless Sensor
  close_on_wireless_lost: Close On Wireless Lost
  child_lock: Child Lock
  # binary sensors to signal wireless sensor discharged and lost
  wireless_sensor_discharged: Wireless Sensors Discharged
  wireless_sensor_lost: Wireless Sensors Lost
  # sensor to show wireless sensors count
  wireless_sensors_count: Wireless Sensors
  # binary sensors to signal wire line 1..4 leaks
  wire_line_leak_1: Leak Toilet
  wire_line_leak_4: Leak Kitchen
  # water counters 1..8 values ("1" - 1st counter at slot1, ..., "8" - 2nd counter at slot4)
  water_counter_1: Water Cold
  water_counter_8: Water Hot

button:
  - platform: restart
    name: ESP Restart
    entity_category: diagnostic

sensor:
  - platform: internal_temperature
    name: ESP Temperature
    entity_category: diagnostic

text_sensor:
  - platform: uptime
    name: ESP Uptime
    format:
      separator: " "
      days: "D"

external_components:
  - source: github://dvb6666/esphome-components
    refresh: 1sec
  - source: github://dvb6666/esphome@homed-last
    components: [ internal_temperature, mqtt]
    refresh: 1sec
