substitutions:
  device_name: "test-polling-component"

esphome:
  name: "${device_name}"
  friendly_name: "${device_name}"

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

logger:
api:
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic

test_polling_component:
  update_interval: 10s # default 10min
  on_update: # automation launched every `update_interval`
    then:
      - logger.log: "Hello World"
      - lambda: |-
          ESP_LOGD("lambda", "lambda(): counter=%d", x);

external_components:
  - source: github://dvb6666/esphome-components
    refresh: 1sec
