esphome:
  name: test-stepper-cover
  friendly_name: test-stepper-cover

esp32:
  board: esp32dev
  framework:
    type: arduino

preferences:
  flash_write_interval: 300s

# Enable logging
logger:

# Enable Home Assistant API
api:
  # encryption:
  #   key: !secret api_key_test

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

cover:
  - platform: stepper_cover
    id: my_cover
    name: Cover
    stepper: my_stepper # шаговик, которым управляем
    restore_max_position: true # будут сохранять в памяти значение "длины шторы", которое будет передаваться в set_max_position()
    max_position: 2000 # "длина" шторы в шагах
    update_delay: 300ms # задержка между публикациями состояния до дефолту (меняется number-ом "Update Delay"; см.ниже)
    # если определены tilt_action или tilt_lambda, в контроле пояится "бегунок" для tilt
    tilt_action:
      - lambda: 'ESP_LOGD("stepper_cover", "tilt_action: %f", tilt);'
    tilt_lambda: |-
      static bool init = false;
      if (!init) {
        ESP_LOGD("stepper_cover", "tilt_lambda: init");
        init = true;
        return 0.3f; // если отдаём конкертное значение (тип float), то будет меняться значение
      }
      return {}; // если отдаём пустоту, ничего происходить не будет

stepper:
  # - platform: a4988
  #   id: my_stepper
  #   step_pin: 12
  #   dir_pin: 14
  #   sleep_pin: 13
  #   max_speed: 650 steps/s
  #   acceleration: 500
  #   deceleration: 500
  - platform: uln2003
    id: my_stepper
    pin_a: 33
    pin_b: 25
    pin_c: 26
    pin_d: 27
    max_speed: 300 steps/s
    sleep_when_done: true
    acceleration: 400
    deceleration: 400

number:
  - platform: template
    # изменение скорости шаговика
    name: Speed Stepper
    optimistic: true
    entity_category: config
    mode: box
    min_value: 100
    max_value: 700
    icon: mdi:cog-transfer
    unit_of_measurement: steps/s
    initial_value: 300
    restore_value: true
    step: 1
    on_value:
      then:
        - lambda: 'id(my_cover).set_speed((int)x);'
  - platform: template
    # изменение задержки между публикациями состояния
    name: Update Delay
    optimistic: true
    entity_category: config
    mode: box
    min_value: 100
    max_value: 10000
    icon: mdi:clock-end
    unit_of_measurement: ms
    initial_value: 500
    restore_value: true
    step: 1
    on_value:
      then:
        - lambda: 'id(my_cover).set_update_delay((uint32_t)x);'

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
  - platform: factory_reset
    name: Factory Reset
    entity_category: diagnostic
  - platform: template
    # тестовое действие по изменению позиции
    name: Set Pos 60 Tilt 80
    on_press:
      then:
        - cover.control:
            id: my_cover
            position: 60%
            tilt: 80%
  - platform: template
    # тестовое действие по изменению "длины шторы" (макс.позиции)
    name: Set Max Pos 3000
    on_press:
      then:
        - lambda: 'id(my_cover).set_max_position(3000);'

external_components:
  - source: github://dvb6666/esphome-components
    refresh: 1sec
